deps: fix the strict_encoding version
➜  rgb-lightning-node git:(master) cargo install --debug --path .
  Installing rgb-lightning-node v0.1.0 (/home/vincent/github/work/rgb-tools/rgb-lightning-node)
    Updating crates.io index
    Updating git repository `https://github.com/RGB-Tools/rgb-lib`
    Updating git repository `https://github.com/arik-so/rust-musig2`
error: failed to compile `rgb-lightning-node v0.1.0 (/home/vincent/github/work/rgb-tools/rgb-lightning-node)`, intermediate artifacts can be found at `/home/vincent/github/work/rgb-tools/rgb-lightning-node/target`

Caused by:
  failed to select a version for `strict_encoding`.
      ... required by package `lightning v0.0.118 (/home/vincent/github/work/rgb-tools/rgb-lightning-node/rust-lightning/lightning)`
      ... which satisfies path dependency `lightning` of package `rgb-lightning-node v0.1.0 (/home/vincent/github/work/rgb-tools/rgb-lightning-node)`
  versions that meet the requirements `=2.6.1` are: 2.6.1

  all possible versions conflict with previously selected packages.

    previously selected package `strict_encoding v2.6.2`
      ... which satisfies dependency `strict_encoding = "=2.6.2"` of package `rgb-lightning-node v0.1.0 (/home/vincent/github/work/rgb-tools/rgb-lightning-node)`

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>